### ISSUE TITLE
Code Samples Are Out of Date

### ISSUE THREAD

**Issue by camsjams** [davetayls/exploring-fp-ts-series#1]
The chaining and usage of fp-ts has changed drastically with the release of version 2+, and the code snippets on this repository and the [blog post](https://davetayls.me/blog/2018/05/20/fp-ts-01-working-with-nullable-values) are out of date.

See https://github.com/gcanti/fp-ts/issues/358

Suggestions:
1. Update code
2. Add a disclaimer on the repo and blog post informing readers that the code samples no longer work on newer versions of fp-ts

**Comment by davetayls** [comment]
hi @camsjams , I'm so sorry this has taken me so long to get back to you. I really wanted to update the code to version 2 but it's been a bit of a crazy year. I've added a note to the readme here and also on the corresponding articles.

I hope you managed to get your code updated ok.

Thanks for letting me know about the changes.
